### ISSUE TITLE
sslerror

### ISSUE THREAD

**Issue by qiao2818** [youfou/hsdata#1]
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure

requests.packages.urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure

requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure

这些错误，如何修正？

**Comment by youfou** [comment]
https连接失败。是获取卡牌数据的时候出现的吧？网络问题，FQ后再试试…
